- name: install packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
      - lxc
    state: present

- name: default.conf
  become: true
  ansible.builtin.copy:
    src: files/default.conf
    dest: /etc/lxc/default.conf
    owner: root
    group: root
    mode: '644'

- name: backups directory
  become: true
  ansible.builtin.file:
    path: /mnt/storage/backups/lxc
    owner: root
    group: root
    mode: '700'
    state: directory

- name: backup script for lxc mail.dasdzoni.com
  become: true
  ansible.builtin.copy:
    src: files/lxc-backup-mail-dasdzoni-com.sh
    dest: /root/scripts
    owner: root
    group: root
    mode: '700'

- name: .env-lxc-backups
  become: true
  ansible.builtin.copy:
    src: files/.env-lxc-backups
    dest: /root/scripts
    owner: root
    group: root
    mode: '600'

- name: add backup script for lxc mail.dasdzoni.com to cron
  become: true
  ansible.builtin.cron:
    name: lxc mail.dasdzoni.com backup
    minute: "01"
    hour: "1"
    user: root
    job: "/root/scripts/lxc-backup-mail-dasdzoni-com.sh > /dev/null 2>&1"

- name: ensure lxc mail.dasdzoni.com is enabled at boot
  become: true
  ansible.builtin.systemd:
    name: lxc@mail.dasdzoni.com
    enabled: yes

- name: backup script for lxc zulip.dasdzoni.com
  ansible.builtin.copy:
    src: files/lxc-backup-zulip-dasdzoni-com.sh
    dest: /root/scripts
    owner: root
    group: root
    mode: '700'

- name: add backup script for lxc zulip.dasdzoni.com to cron
  ansible.builtin.cron:
    name: lxc zulip.dasdzoni.com backup
    minute: "11"
    hour: "1"
    user: root
    job: "/root/scripts/lxc-backup-zulip-dasdzoni-com.sh > /dev/null 2>&1"

- name: ensure lxc zulip.dasdzoni.com is enabled at boot
  ansible.builtin.systemd:
    name: lxc@zulip.dasdzoni.com
    enabled: yes
