- name: install packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: wireguard-tools
    state: present

- name: wg-dasdzoni
  become: true
  ansible.builtin.copy:
    src: files/wg-dasdzoni.conf
    dest: /etc/wireguard/wg-dasdzoni.conf
    owner: root
    group: root
    mode: '600'
  notify: restart wg-dasdzoni

- name: ensure wg-quick@wg-dasdzoni.service is started and enabled at boot
  become: true
  ansible.builtin.systemd:
    name: wg-quick@wg-dasdzoni.service
    state: started
    enabled: yes
