- name: restart sshd
  become: true
  systemd: "name=sshd state=restarted"

- name: restart iptables
  become: true
  systemd: "name=netfilter-persistent state=restarted"

- name: restart docker
  become: true
  systemd: "name=docker state=restarted"
